name: build PWA app

on:
  push:
    branches: [ master ]
    
env:
    source_path: source
    page_path: page
    build_path: build
    target_branch: gh-pages

jobs:
  update_gh-page:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        path: ${{source_path}}

    - name: setup node Version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: build angular app
      run: |
        npm install --prefix ${{source_path}}
        npm run build --prefix ${{source_path}} -- --prod --base-href="/APP5-RC-upsaclay.github.io/" --output-path="${{build_path}}"
    
    - name: Checkout ${{target_branch}} branch
      uses: actions/checkout@v2
      with:
        ref: ${{target_branch}}
        path: ${{page_path}}
    
    - name: update ${{target_branch}} with builded angular app
      run: |
        rm -r ${{page_path}}/*
        cp -r ${{source_path}}/${{build_path}}/* ${{page_path}}
    
    - name: Commit
      run: |
        cd ${{page_path}}
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "new version of the pwa"
        
    - name: Push changes to ${{target_branch}} branche
      uses: ad-m/github-push-action@master
      with:
        branch: ${{target_branch}}
        directory: ${{page_path}}
        github_token: ${{ secrets.GITHUB_TOKEN }}
